server:
  port: 8010

# 申明 服务降级
feign:
  hystrix:
    enabled: true
# 设置 feign 的超时时间 超过 5s 进行降级返回
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000
# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.137.1:3306/conlon_cloud?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化连接池
      initial-size: 5
      #连接池最小
      min-idle: 5
      #最大
      max-active: 30
      #检测关闭空闲连接 单位 hs
      time-between-eviction-runs-millis: 60000
      #去掉后 . 监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall

  application:
    # 应用程序名称，后面会在消费者中用到
    name: @build.finalName@

# mybatis-plus 配置
mybatis-plus:
  mapper-locations: conlon/cloud/user/dao/mapper/*.xml
  type-aliases-package: conlon.cloud.auth.entity
  global-config:
    db-config:
      id-type: auto

# 注册到eureka
eureka:
  instance:
    # 可以使用ip注册
    preferIpAddress: true
  client:
    serviceUrl:
      ## 注册到 eureka (这里需要自己配置host 和 nginx)
      defaultZone: http://eureka01.ms.svc.cluster.local:8888/eureka/,http://eureka02.ms.svc.cluster.local:8888/eureka/

# 定义日志级别  debug , info
logback:
  #  使用 pom当中的参数
  name: ${spring.application.name}
  path: /home/cloud/${logback.name}/
  level: info

# 配置日志
logging:
  config: classpath:logback-user.xml
  level:
    conlon.cloud.common.dao : debug
    conlon.cloud.user.dao : debug
